#!/bin/bash

set -e

cd "$(dirname "$0")/../builtinFonts"

echo "// The contents of this file are generated by ./lib/EpdFont/scripts/build-font-ids.sh"
echo "#pragma once"
echo ""

echo "#define EDSLAB_12_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./edslab_12_regular.h",
  "./edslab_12_bold.h",
  "./edslab_12_bolditalic.h",
  "./edslab_12_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define EDSLAB_14_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./edslab_14_regular.h",
  "./edslab_14_bold.h",
  "./edslab_14_bolditalic.h",
  "./edslab_14_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define EDSLAB_16_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./edslab_16_regular.h",
  "./edslab_16_bold.h",
  "./edslab_16_bolditalic.h",
  "./edslab_16_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define EDSLAB_18_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./edslab_18_regular.h",
  "./edslab_18_bold.h",
  "./edslab_18_bolditalic.h",
  "./edslab_18_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define EDSLAB_8_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./edslab_8_regular.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define NOTOSANS_12_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./notosans_12_regular.h",
  "./notosans_12_bold.h",
  "./notosans_12_bolditalic.h",
  "./notosans_12_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define NOTOSANS_14_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./notosans_14_regular.h",
  "./notosans_14_bold.h",
  "./notosans_14_bolditalic.h",
  "./notosans_14_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define NOTOSANS_16_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./notosans_16_regular.h",
  "./notosans_16_bold.h",
  "./notosans_16_bolditalic.h",
  "./notosans_16_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define NOTOSANS_18_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./notosans_18_regular.h",
  "./notosans_18_bold.h",
  "./notosans_18_bolditalic.h",
  "./notosans_18_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define EDSLAB_UI_11_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./edslab_ui_11_regular.h",
  "./edslab_ui_11_bold.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define EDSLAB_UI_12_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./edslab_ui_12_regular.h",
  "./edslab_ui_12_bold.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define EDSLAB_UI_8_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./edslab_ui_8_regular.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define LEGACY_UI_10_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./ubuntu_10_regular.h",
  "./ubuntu_10_bold.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define LEGACY_UI_12_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./ubuntu_12_regular.h",
  "./ubuntu_12_bold.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define LEGACY_UI_8_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./notosans_8_regular.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

cat <<'EOF'

#if CROSSLINGUA_UI_EDSLAB
#define UI_11_FONT_ID EDSLAB_UI_11_FONT_ID
#define UI_12_FONT_ID EDSLAB_UI_12_FONT_ID
#define SMALL_FONT_ID EDSLAB_UI_8_FONT_ID
#else
#define UI_10_FONT_ID LEGACY_UI_10_FONT_ID
// The legacy UI has no 11 pt face; keep the alias valid for non-EdsLab builds.
#define UI_11_FONT_ID LEGACY_UI_10_FONT_ID
#define UI_12_FONT_ID LEGACY_UI_12_FONT_ID
#define SMALL_FONT_ID LEGACY_UI_8_FONT_ID
#endif

// Font ID 0 is reserved as the "not found" sentinel.
// Guard against any hash accidentally producing 0.
static_assert(EDSLAB_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(EDSLAB_14_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(EDSLAB_16_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(EDSLAB_18_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(EDSLAB_8_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSANS_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSANS_14_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSANS_16_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSANS_18_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(UI_11_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(UI_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(SMALL_FONT_ID != 0, "Font ID collision with sentinel");
EOF
