#pragma once

#include <builtinFonts/edslab_8_regular.h>
#include <builtinFonts/edslab_12_bold.h>
#include <builtinFonts/edslab_12_bolditalic.h>
#include <builtinFonts/edslab_12_italic.h>
#include <builtinFonts/edslab_12_regular.h>
#include <builtinFonts/edslab_14_bold.h>
#include <builtinFonts/edslab_14_bolditalic.h>
#include <builtinFonts/edslab_14_italic.h>
#include <builtinFonts/edslab_14_regular.h>
#include <builtinFonts/edslab_16_bold.h>
#include <builtinFonts/edslab_16_bolditalic.h>
#include <builtinFonts/edslab_16_italic.h>
#include <builtinFonts/edslab_16_regular.h>
#include <builtinFonts/edslab_18_bold.h>
#include <builtinFonts/edslab_18_bolditalic.h>
#include <builtinFonts/edslab_18_italic.h>
#include <builtinFonts/edslab_18_regular.h>
#include <builtinFonts/edslab_ui_8_regular.h>
#include <builtinFonts/edslab_ui_10_bold.h>
#include <builtinFonts/edslab_ui_10_regular.h>
#include <builtinFonts/edslab_ui_12_bold.h>
#include <builtinFonts/edslab_ui_12_regular.h>
#include <builtinFonts/notosans_8_regular.h>
#include <builtinFonts/notosans_12_bold.h>
#include <builtinFonts/notosans_12_bolditalic.h>
#include <builtinFonts/notosans_12_italic.h>
#include <builtinFonts/notosans_12_regular.h>
#include <builtinFonts/notosans_14_bold.h>
#include <builtinFonts/notosans_14_bolditalic.h>
#include <builtinFonts/notosans_14_italic.h>
#include <builtinFonts/notosans_14_regular.h>
#include <builtinFonts/notosans_16_bold.h>
#include <builtinFonts/notosans_16_bolditalic.h>
#include <builtinFonts/notosans_16_italic.h>
#include <builtinFonts/notosans_16_regular.h>
#include <builtinFonts/notosans_18_bold.h>
#include <builtinFonts/notosans_18_bolditalic.h>
#include <builtinFonts/notosans_18_italic.h>
#include <builtinFonts/notosans_18_regular.h>
#include <builtinFonts/ubuntu_10_bold.h>
#include <builtinFonts/ubuntu_10_regular.h>
#include <builtinFonts/ubuntu_12_bold.h>
#include <builtinFonts/ubuntu_12_regular.h>
