#pragma once

#include <builtinFonts/bookerly_12_bold.h>
#include <builtinFonts/bookerly_12_bolditalic.h>
#include <builtinFonts/bookerly_12_italic.h>
#include <builtinFonts/bookerly_12_regular.h>
#include <builtinFonts/bookerly_14_bold.h>
#include <builtinFonts/bookerly_14_bolditalic.h>
#include <builtinFonts/bookerly_14_italic.h>
#include <builtinFonts/bookerly_14_regular.h>
#include <builtinFonts/bookerly_16_bold.h>
#include <builtinFonts/bookerly_16_bolditalic.h>
#include <builtinFonts/bookerly_16_italic.h>
#include <builtinFonts/bookerly_16_regular.h>
#include <builtinFonts/bookerly_18_bold.h>
#include <builtinFonts/bookerly_18_bolditalic.h>
#include <builtinFonts/bookerly_18_italic.h>
#include <builtinFonts/bookerly_18_regular.h>
#include <builtinFonts/notosans_8_regular.h>
#include <builtinFonts/edslab_10_regular.h>
#include <builtinFonts/edslab_12_regular.h>
#include <builtinFonts/edslab_14_regular.h>
#include <builtinFonts/edslab_16_regular.h>
#include <builtinFonts/edslab_18_regular.h>
#include <builtinFonts/alegreya_12_regular.h>
#include <builtinFonts/alegreya_14_regular.h>
#include <builtinFonts/alegreya_16_regular.h>
#include <builtinFonts/alegreya_18_regular.h>
#include <builtinFonts/gpro_12_regular.h>
#include <builtinFonts/gpro_14_regular.h>
#include <builtinFonts/gpro_16_regular.h>
#include <builtinFonts/gpro_18_regular.h>
#include <builtinFonts/ubuntu_10_bold.h>
#include <builtinFonts/ubuntu_10_regular.h>
#include <builtinFonts/ubuntu_12_bold.h>
#include <builtinFonts/ubuntu_12_regular.h>
