// The contents of this file are generated by ./lib/EpdFont/scripts/build-font-ids.sh
#pragma once

#define EDSLAB_12_FONT_ID (1645029000)
#define EDSLAB_14_FONT_ID (74628825)
#define EDSLAB_16_FONT_ID (1254269735)
#define EDSLAB_18_FONT_ID (1998947179)
#define EDSLAB_8_FONT_ID (1404225414)
#define NOTOSANS_12_FONT_ID (2057568286)
#define NOTOSANS_14_FONT_ID (-1589315735)
#define NOTOSANS_16_FONT_ID (1669013660)
#define NOTOSANS_18_FONT_ID (37077304)
#define UI_10_FONT_ID (-350896663)
#define UI_12_FONT_ID (-884914451)
#define SMALL_FONT_ID (-2057420480)

// Font ID 0 is reserved as the "not found" sentinel.
// Guard against any hash accidentally producing 0.
static_assert(EDSLAB_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(EDSLAB_14_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(EDSLAB_16_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(EDSLAB_18_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(EDSLAB_8_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSANS_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSANS_14_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSANS_16_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSANS_18_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(UI_10_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(UI_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(SMALL_FONT_ID != 0, "Font ID collision with sentinel");
